### PR TITLE
use spottoken renewer from the datamechanics jupyter_server fork v2.5.0

### PR DESCRIPTION
**Pull request by sigmarkarl**
Use spot token renewer using request from context var

# Jira Ticket

[BGD-4169](https://spotinst.atlassian.net/browse/BGD-4169)

# Checklist:
- [x] I have filled relevant self assessment ([NodeJS](https://docs.google.com/forms/d/e/1FAIpQLSfl14u9AOBAmxVJ272tvO7XNuXE-EMvWaGcaRZalu1UAKB7RA/viewform), [Frontend](https://docs.google.com/forms/d/e/1FAIpQLSdiBPNKH81w_EkavihVL8Uwb0j7tP8PwJmLFYm2nCOQxz-1qw/viewform), [Backend](https://docs.google.com/forms/d/e/1FAIpQLSed_PsTJ5-XIWkFL6BSDE2AQRBVPmwc3PAmHZkUn-erzVI37Q/viewform?usp=sf_link))
- [x] I have run ESlint on my changes and fixed all warnings and errors (**NodeJS & Frontend Services**)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have validated all the requirements in the Jira task were answered
- [x] I have all neccessary approvals for the design/mini design of this task
- [ ] I have approved the API changes and granular permission patterns (documentation subtask) (**For public services only**) 

[BGD-4169]: https://spotinst.atlassian.net/browse/BGD-4169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sigmarkarl** [comment]
use protected branch instead of main

**Review by epignot — COMMENTED** [review]
it looks ok to me, but I'm struggling to remember how the version number here correlates to images built in `bigdata-infrastructure`
@sigmarkarl  @arnarpall

**Comment by sigmarkarl** [comment]
> it looks ok to me, but I'm struggling to remember how the version number here correlates to images built in `bigdata-infrastructure` @sigmarkarl @arnarpall

its doesn't correlate. isn't it just the image tag that counts

**Comment by arnarpall** [comment]
Yeah when I set the `appVersion` I tied it to the jupyter stacks base notebook tag, but actually forgot to change it when I had to move to 3.6.x of jupyter.

**Review by ImpSy — APPROVED** [review]

**Pull request merged**
